### ISSUE TITLE
cookie_options.path does not seem to be used in any meaningful way

### ISSUE THREAD

**Issue by cilphex** [defunctzombie/node-yummy#5]

**Comment by defunctzombie** [comment]
It should be passed to the cookie module but maybe that isn't happening. Is it causing an issue? Presumably you are wanting to set a custom path?

**Comment by cilphex** [comment]
The problem is actually that we're setting path to `/` but getting the cookie set on other paths anyway. e.g. Here it got set for both `/` and `/trade`:

![czvtwpd4-a15lbq2qs5j3jvb6ahwkovt6s4yfq8pfb0](https://cloud.githubusercontent.com/assets/611803/11726508/d7ac85a0-9f33-11e5-9e27-0756a9054fea.png)

**Comment by cilphex** [comment]
This started happening after we changed the `/trade` URL styles from `/trade?product_id=BTC-USD` to `/trade/BTC-USD`. The 2nd cookie is created if you (1) have the trade page open, signed in; (2) sign out of coinbase in another window (3) refresh your trade view.

The interesting thing is, for (3) if instead of refreshing, you visit `/trade/BTC-USD/xyz`, the cookie path will not be `/trade`, it will be `/trade/BTC-USD`. So `/` seems to not be absolute - it's relative to the last part of the path.

**Comment by defunctzombie** [comment]
Strange that the cookie is set to a relative path, my understanding is/was that path is suppose to be absolute. Is path maybe not actually being set?

**Comment by cilphex** [comment]
That could be, not sure yet.

**Comment by cilphex** [comment]
I have a potential fix: https://github.com/defunctzombie/node-yummy/pull/6

**Comment by defunctzombie** [comment]
https://github.com/defunctzombie/node-yummy/commit/0a7ab09ef022e5549409a731d37237d7fed9cd72
