### ISSUE TITLE
Re-enable Hot Pocket tweeting feature

### ISSUE THREAD

**Issue by TheJaredWilcurt** [defunctzombie/node-yummy#7]
This was one of the primary reasons why I used this repo as a dependency.

Many others are upset that this feature was removed:
- https://medium.com/@jaredcheeda/it-seems-as-though-yummy-js-1364152936fe

**Comment by grzesiekrzaca** [comment]
Hehe that was funny (came here from the article to see what Yummy really is)

**Comment by jdan** [comment]
I am so sorry about this.

**Comment by defunctzombie** [comment]
Really confused. This module doesn't have that like-tweet js file... This must be some other yummy module people are installing? Or am I missing something.

**Comment by grzesiekrzaca** [comment]
read the linked article :D (search for Guy Fieri :P)

**Comment by TheJaredWilcurt** [comment]
FINE! I'll make my own repo... with black jack... and hot pockets!

ya know what, forget the black jack

... actually ya know what, forget the whole thing.

**Comment by yanzou** [comment]
LOL

**Comment by Hum4n01d** [comment]
Wow

**Comment by adrianovalente** [comment]
Please re-enable it

**Comment by ghost** [comment]
this ruins my entire build
